import Layout from '@/components/Layout';
import { metadata } from '@/shared/data';
import { _docs as Container } from '@/styles/routes/_docs';

export default function PrivacyPolicy() {
  const { author } = metadata;

  return (
    <Layout renderFooter renderHeader>
      <Container>
        <section className='wrapper-container'>
          <h1>Privacy Policy</h1>
          <p>Last updated: November 17, 2023</p>
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of your information when you use the
            Service and tells you about your privacy rights and how the law
            protects you.
          </p>
          <p>
            We use your Personal data to provide and improve the Service. By
            using the Service, you agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <strong>Account</strong> means a unique account created for you to
              access our Service or parts of our Service.
            </li>

            <li>
              <strong>Application</strong> refers to Choconotey, the software
              program provided by the Company.
            </li>
            <li>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
              in this Agreement) refers to Choconotey.
            </li>
            <li>
              <strong>Country</strong> refers to: Mozambique.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Application.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
          <h2>Collecting and Using your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask you to provide Us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that you visit, the time and date of your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When you access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile device
            unique ID, the IP address of your mobile device, your mobile
            operating system, the type of mobile Internet browser you use,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access the Service by or through a
            mobile device.
          </p>
          <h3>Use of your Personal Data</h3>
          <p>We may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage your Account:</strong> to manage your
              registration as a user of the Service. The Personal Data you
              provide can give you access to different functionalities of the
              Service that are available to you as a registered user.
            </li>
            <li>
              <strong>To contact you:</strong> To contact you by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </li>

            <li>
              <strong>To manage your requests:</strong> To attend and manage
              your requests to Us.
            </li>
          </ul>

          <h3>Retention of your Personal Data</h3>
          <p>
            No data will still be available or hold in our servers once deleted
            by you in all cases.
          </p>
          <p>
            We will take all steps reasonably necessary to ensure that your data
            is treated securely and in accordance with this Privacy Policy and
            no transfer of your Personal Data will take place to an organization
            or a country unless there are adequate controls in place including
            the security of your data and other personal information.
          </p>
          <h3>Delete your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about you.
          </p>
          <p>
            Our Service may give you the ability to delete certain information
            about you from within the Service.
          </p>
          <p>
            You may update, amend, or delete your information at any time by
            signing in to your Account, if you have one, and visiting the
            account settings section that allows you to manage your personal
            information. you may also contact Us to request access to, correct,
            or delete any personal information that you have provided to Us.
          </p>
          <h3>Disclosure of your Personal Data</h3>
          <h4>Business Transactions</h4>
          <p>
            If the Company is involved in a merger, acquisition or asset sale,
            your Personal Data may be transferred. We will provide notice before
            your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>
          <h4>Law enforcement</h4>
          <p>
            Under certain circumstances, the Company may be required to disclose
            your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </p>
          <h4>Other legal requirements</h4>
          <p>
            We may disclose your Personal Data in the good faith belief that
            such action is necessary to:
          </p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>
              Protect the personal safety of Users of the Service or the public
            </li>
            <li>Protect against legal liability</li>
          </ul>
          <h3>Security of your Personal Data</h3>
          <p>
            The security of your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect your Personal Data, We
            cannot guarantee its absolute security.
          </p>

          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not
            operated by Us. If you click on a third party link, you will be
            directed to that third party's site. We strongly advise you to
            review the Privacy Policy of every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            We will let you know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the
            &quot;Last updated&quot; date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, you can contact
            us at <strong>{author.email}</strong>.
          </p>
        </section>
      </Container>
    </Layout>
  );
}
